### ISSUE TITLE
Streaming seems to stop working after about 3 minutes

### ISSUE THREAD

**Issue by evanccnyc** [micahg/plugin.video.mlslive#1]
The addon doesnt freeze (sometimes it dumps me out sometimes it just sits there). If I restart the stream it works, so I think there is some sort of authentication timeout going on.

**Comment by micahg** [comment]
I'm aware. Unfortunately, it seems to be a problem with authentication failing when requesting the keys in the m3u8 file.

Previously there was one key at the start of the m3u8 file for a particular bandwidth. Now there is a new one every 30 segments (5 minutes worth of video).

I need to investigate more to see why the authentication is failing but the fix is likely in FFMPEG or XBMC, not this plugin.

**Comment by evanccopengeo** [comment]
It might be worth trying to use the android streams. I think they might not have the continuous authentication the same way.

**Comment by chieftainblackbear** [comment]
It looks like this might be fixed in Kodi/XBMC 15. Just installed Beta 1 which updates FFMPEG. Haven't seen any issues with the HOU v LAG game so far.

**Comment by micahg** [comment]
Indeed it is. Guess who's name you'll see on the FFMPEG fix ;)
